version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Ensure this matches the path to your Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Ensure this matches the path to your Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    working_dir: /app
